services:
  db:
    container_name: readora-database
    image: postgres:16.1-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - volume:/var/lib/postgresql/data
    networks:
      - network

volumes:
  volume:
networks:
  network:
