# There's no database service in this file. This is because database managed seperately in production environment.

services:
  app:
    container_name: readora-app
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - network
  redis:
    container_name: readora-redis
    image: redis:7.4-alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
    networks:
      - network

volumes:
  redis:

networks:
  network:
